export type User = {
    id: string;
    ac: BigInt;
    mandal: string;
    vId: BigInt;
    vName: string;
    loc: string;
    booths:string
}

export const fakeData: User[] = [
  {
    id:"101a",
    ac: 30,
    mandal: "Marudhar",
    vId: 1,
    vName: "Sham Nagar",
    loc: 'Kasar',
    booths:"1,2,3",
  },
  {
    id:"102a",
    ac: 30,
    mandal: "Marudhar",
    vId: 1,
    vName: "Sham Nagar",
    loc: 'pungva',
    booths:"4,5,6",
  },
  {
    id:"103a",
    ac: 30,
    mandal: "Marudhar",
    vId: 1,
    vName: "Sham Nagar",
    loc: 'Sirana',
    booths:"7,8,9",
  },
  {
    id:"104a",
    ac: 30,
    mandal: "Marudhar",
    vId: 2,
    vName: "Hazargul",
    loc: 'Vidhan',
    booths:"10,11,12",
  },
  {
    id:"105a",
    ac: 30,
    mandal: "Marudhar",
    vId: 2,
    vName: "Hazarigul",
    loc: 'Madau',
    booths:"13,14",
  },
  {
    id:"106a",
    ac: 30,
    mandal: "Khadi Road",
    vId: 3,
    vName: "Badna",
    loc: 'Vilom namgar',
    booths:"15,16",
  },
  {
    id:"107a",
    ac: 30,
    mandal: "Khadi Road",
    vId: 3,
    vName: "Badna",
    loc: 'Shakha',
    booths:"17,18",
  },
  {
    id:"108a",
    ac: 30,
    mandal: "Khadi Road",
    vId: 3,
    vName: "Badna",
    loc: 'shim',
    booths:"19,20",
  },
  {
    id:"109a",
    ac: 30,
    mandal: "Bharti gauo",
    vId: 4,
    vName: "Kasar nagar",
    loc: 'Sikoli',
    booths:"21, 22, 23",
  },
  {
    id:"110a",
    ac: 30,
    mandal: "Marudhar",
    vId: 1,
    vName: "Sham Nagar",
    loc: 'Kasar',
    booths:"1,2,3",
  },
  {
    id:"111a",
    ac: 30,
    mandal: "Marudhar",
    vId: 1,
    vName: "Sham Nagar",
    loc: 'pungva',
    booths:"4,5,6",
  },
  {
    id:"112a",
    ac: 30,
    mandal: "Marudhar",
    vId: 1,
    vName: "Sham Nagar",
    loc: 'Sirana',
    booths:"7,8,9",
  },
  {
    id:"113a",
    ac: 30,
    mandal: "Marudhar",
    vId: 2,
    vName: "Hazargul",
    loc: 'Vidhan',
    booths:"10,11,12",
  },
  {
    id:"114a",
    ac: 30,
    mandal: "Marudhar",
    vId: 2,
    vName: "Hazarigul",
    loc: 'Madau',
    booths:"13,14",
  },
  {
    id:"115a",
    ac: 30,
    mandal: "Khadi Road",
    vId: 3,
    vName: "Badna",
    loc: 'Vilom namgar',
    booths:"15,16",
  },
  {
    id:"116a",
    ac: 30,
    mandal: "Khadi Road",
    vId: 3,
    vName: "Badna",
    loc: 'Shakha',
    booths:"17,18",
  },
  {
    id:"117a",
    ac: 30,
    mandal: "Khadi Road",
    vId: 3,
    vName: "Badna",
    loc: 'shim',
    booths:"19,20",
  },
  {
    id:"118a",
    ac: 30,
    mandal: "Bharti gauo",
    vId: 4,
    vName: "Kasar nagar",
    loc: 'Sikoli',
    booths:"21, 22, 23",
  },
  {
    id:"119a",
    ac: 30,
    mandal: "Marudhar",
    vId: 1,
    vName: "Sham Nagar",
    loc: 'Kasar',
    booths:"1,2,3",
  },
  {
    id:"120a",
    ac: 30,
    mandal: "Marudhar",
    vId: 1,
    vName: "Sham Nagar",
    loc: 'pungva',
    booths:"4,5,6",
  },
  {
    id:"121a",
    ac: 30,
    mandal: "Marudhar",
    vId: 1,
    vName: "Sham Nagar",
    loc: 'Sirana',
    booths:"7,8,9",
  },
  {
    id:"122a",
    ac: 30,
    mandal: "Marudhar",
    vId: 2,
    vName: "Hazargul",
    loc: 'Vidhan',
    booths:"10,11,12",
  },
  {
    id:"123a",
    ac: 30,
    mandal: "Marudhar",
    vId: 2,
    vName: "Hazarigul",
    loc: 'Madau',
    booths:"13,14",
  },
  {
    id:"124a",
    ac: 30,
    mandal: "Khadi Road",
    vId: 3,
    vName: "Badna",
    loc: 'Vilom namgar',
    booths:"15,16",
  },
  {
    id:"125a",
    ac: 30,
    mandal: "Khadi Road",
    vId: 3,
    vName: "Badna",
    loc: 'Shakha',
    booths:"17,18",
  },
  {
    id:"126a",
    ac: 30,
    mandal: "Khadi Road",
    vId: 3,
    vName: "Badna",
    loc: 'shim',
    booths:"19,20",
  },
  {
    id:"127a",
    ac: 30,
    mandal: "Bharti gauo",
    vId: 4,
    vName: "Kasar nagar",
    loc: 'Sikoli',
    booths:"21, 22, 23",
  },
  {
    id:"128a",
    ac: 30,
    mandal: "Marudhar",
    vId: 1,
    vName: "Sham Nagar",
    loc: 'Kasar',
    booths:"1,2,3",
  },
  {
    id:"129a",
    ac: 30,
    mandal: "Marudhar",
    vId: 1,
    vName: "Sham Nagar",
    loc: 'pungva',
    booths:"4,5,6",
  },
  {
    id:"130a",
    ac: 30,
    mandal: "Marudhar",
    vId: 1,
    vName: "Sham Nagar",
    loc: 'Sirana',
    booths:"7,8,9",
  },
  {
    id:"131a",
    ac: 30,
    mandal: "Marudhar",
    vId: 2,
    vName: "Hazargul",
    loc: 'Vidhan',
    booths:"10,11,12",
  },
  {
    id:"132a",
    ac: 30,
    mandal: "Marudhar",
    vId: 2,
    vName: "Hazarigul",
    loc: 'Madau',
    booths:"13,14",
  },
  {
    id:"133a",
    ac: 30,
    mandal: "Khadi Road",
    vId: 3,
    vName: "Badna",
    loc: 'Vilom namgar',
    booths:"15,16",
  },
  {
    id:"134a",
    ac: 30,
    mandal: "Khadi Road",
    vId: 3,
    vName: "Badna",
    loc: 'Shakha',
    booths:"17,18",
  },
  {
    id:"135a",
    ac: 30,
    mandal: "Khadi Road",
    vId: 3,
    vName: "Badna",
    loc: 'shim',
    booths:"19,20",
  },
  {
    id:"136a",
    ac: 30,
    mandal: "Bharti gauo",
    vId: 4,
    vName: "Kasar nagar",
    loc: 'Sikoli',
    booths:"21, 22, 23",
  },
  {
    id:"137a",
    ac: 30,
    mandal: "Marudhar",
    vId: 1,
    vName: "Sham Nagar",
    loc: 'Kasar',
    booths:"1,2,3",
  },
  {
    id:"138a",
    ac: 30,
    mandal: "Marudhar",
    vId: 1,
    vName: "Sham Nagar",
    loc: 'pungva',
    booths:"4,5,6",
  },
  {
    id:"139a",
    ac: 30,
    mandal: "Marudhar",
    vId: 1,
    vName: "Sham Nagar",
    loc: 'Sirana',
    booths:"7,8,9",
  },
  {
    id:"140a",
    ac: 30,
    mandal: "Marudhar",
    vId: 2,
    vName: "Hazargul",
    loc: 'Vidhan',
    booths:"10,11,12",
  }
]